version: '3'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/var/www/html
    working_dir: /var/www/html
    networks:
      - laravel

  web:
    image: nginx:latest
    volumes:
      - .:/var/www/html
      - ./default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "8080:80"
    depends_on:
      - app
    networks:
      - laravel

  db_mysql_1:
    image: arm64v8/mysql
    container_name: db_mysql_1
    environment:
      MYSQL_ROOT_PASSWORD: en_plus_secret
      MYSQL_DATABASE: en_plus
      MYSQL_USER: en_plus
      MYSQL_PASSWORD: enplus_dev2022
    ports:
      - "3306:3306"
    networks:
      - laravel

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    platform: linux/amd64
    environment:
      PMA_HOST: db
      PMA_USER: root
      PMA_PASSWORD: root
    ports:
      - "8081:80"
    networks:
      - laravel

networks:
  laravel:
